site_name: Awesome Go Educations
site_url: https://github.com/mehdihadeli/awesome-go-education
site_description: A curated list of awesome articles and resources for learning and practicing about Go and its related technologies.
docs_dir:
repo_name: mehdihadeli/awesome-go-education
repo_url: https://github.com/mehdihadeli/awesome-go-education
edit_uri: edit/main/docs/
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  prev_next_buttons_location: both
  navigation_depth: 4
  titles_only: False
  sticky_navigation: True
markdown_extensions:
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:pymdownx.emoji.twemoji
  #    emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #- pymdownx.emoji:
  #    emoji_index: !!python/name:materialx.emoji.twemoji
  #    emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: true

nav:
  - WEB:
    - WEB / REST : web/web-rest.md
    - Server: web/server.md
    - Status Code : web/status-code.md
    - Header : web/header.md
    - Http Client :  web/http-client.md
    - Http Handler :  web/http-handler.md
    - Middleware :  web/middleware.md
    - Mux & Router :  web/mux-router.md
    - Rate Limiting :  web/rate-limiting.md
    - Response :  web/response.md
    - Versioning :  web/versioning.md
  - Go Instructions:
    - Go: go-instructions/go.md
    - Control Flow: go-instructions/control-flow.md
    - Conversion: go-instructions/conversion.md
    - Dep: go-instructions/dep.md
    - Function:
      - Function: go-instructions/functions/function.md
      - Anonymouse Functions: go-instructions/functions/anonymouse-functions.md
      - Closures: go-instructions/functions/closures.md
      - First Class Functions: go-instructions/functions/first-class-functions.md
      - Variadic Functions: go-instructions/functions/variadic-functions.md
      - Defer: go-instructions/functions/defer.md
    - Database:
      - Database: database/database.md
      - Migration: database/migration.md
      - ORM:
        - ORM: database/orm/orm.md
        - gorm: database/orm/gorm.md
    - Init: go-instructions/init.md
    - Interface:
      - Interface: go-instructions/interface/interface.md
      - Type Assertion: go-instructions/interface/type-assertion.md
      - Type Switch: go-instructions/interface/type-switch.md
      - Embedding: go-instructions/interface/embedding.md
    - Loops: go-instructions/loops.md
    - Pointer: go-instructions/pointer.md
    - Struct:
      - Struct: go-instructions/struct/struct.md
      - Struct Tags: go-instructions/struct/struct-tags.md
      - Method: go-instructions/struct/method.md
    - Switch: go-instructions/switch.md  
    - Generics: go-instructions/generics.md
    - Variables: go-instructions/variables.md
    - New & Make: go-instructions/new-make.md
    - Enums: go-instructions/enum.md
    - Data Types:
      - Data Types: go-instructions/data-types/data-types.md
      - Strings: go-instructions/data-types/strings.md
    - Collections:
      - Array: go-instructions/collections/arrays.md
      - Maps: go-instructions/collections/maps.md
      - Slices: go-instructions/collections/slices.md
  - ORM:
    - ORM: database/orm/orm.md
    - gorm: database/orm/gorm.md
  - Logging: logging.md
  - DDD: ddd.md
  - Repository: repository.md
  - Clean Architecture: clean-architecture.md
  - CQRS: cqrs.md
  - Event Sourcing: event-sourcing.md
  - Concurrency:
    - Concurrency: concurrency/concurrency.md
    - Goroutines: concurrency/goroutines.md
    - Channels: concurrency/channel.md
    - Buffered Channels: concurrency/buffered-channels.md
    - Range-Close: concurrency/range-close.md
    - Wait Group: concurrency/wait-group.md
    - Deadlock: concurrency/deadlock.md
    - Select: concurrency/select.md
    - Mutex: concurrency/mutex.md
  - Best Practices: best-practices.md
  - Error Handling:
    - Error Handling: error/error-handling.md
    - Panic: error/panic.md
  - File: file.md
  - Modules & Packages: modules-packages.md
  - Json: json.md
  - gRPC: gRPC.md
  - Context: context.md
  - Microservices : microservices.md
  - Service Discovery : service-discovery.md
  - Tracing: tracing.md
  - OOP : oop.md
  - Project Layout & Structure : project-layout-structure.md
  - API Documentation: api-documentation.md
  - Profiling: profiling.md
  - Debugging: debugging.md
  - Reflection: reflection.md
  - Elastic Search: elastic.md
  - Anti Patterns: anti-patterns.md
  - Test: test.md
  - Docker Kubernetes: docker-kubernetes.md
  - Software Architecture : software-architecture.md
  - Build & Install: build-install.md
  - Workspace && GOPATH: workspace-gopath.md
  - Package Management: package-management.md
  - Tools: tools.md
  - Formatters: formatters.md
  - CLI: cli.md
  - CI/CD: ci-cd.md
  - Resources: resources.md
  - Others: 
    - Flag: others/flag.md

copyright: 2021 <a href="https://github.com/mehdihadeli">Mehdi Hadeli</a>.
#remote_branch: gh-pages
#remote_name: origin
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mehdi_hadeli
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mehdihadeli
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mehdihadeli
